language: rust
sudo: required
os:
  - linux
  - osx
rust:
  - nightly
services:
  - docker
before_deploy: "./tools/build-release rssbot ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: "..."
  file_glob: true
  file: "rssbot-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    rust: stable
    tags: true
