[package]
name = "rssbot"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
error-chain = "0.9"
quick-xml = "0.6"
lazy_static = "0.2"
regex = "0.2"
pinyin-order = "0.1"

telebot = { path = "./telebot" }
# version specified by telebot
serde = "*"
serde_derive = "*"
serde_json = "*"
curl = "*"
futures = "*"
tokio-core = "*"
tokio-curl = "*"